export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_RESET_PASSWORD = 'USER_RESET_PASSWORD';
export const GET_USER_CATEGORIES = 'GET_USER_CATEGORIES';
export const GET_USER_RECIPES = 'GET_USER_RECIPES';
export const SEARCH_USER_CATEGORIES = 'SEARCH_USER_CATEGORIES';
export const SEARCH_USER_RECIPES = 'SEARCH_USER_RECIPES';